#' Load a SingleCellExperiment
#'
#' Load a \linkS4class{SingleCellExperiment} object from file, using the metadata generated by the corresponding \code{\link{stageObject}} method.
#'
#' @param exp.info Named list containing the metadata for this experiment.
#' @param project Any argument accepted by the acquisition functions, see \code{?\link{acquireFile}}. 
#' By default, this should be a string containing the path to a staging directory.
#' @param ... Further arguments to pass to \code{\link{loadSummarizedExperiment}}.
#' 
#' @return A \linkS4class{SingleCellExperiment} object.
#'
#' @author Aaron Lun
#'
#' @examples
#' # Mocking up an SCE:
#' mat <- matrix(rpois(10000, 10), ncol=10)
#' colnames(mat) <- letters[1:10]
#' rownames(mat) <- sprintf("GENE_%i", seq_len(nrow(mat)))
#'
#' se <- SingleCellExperiment(list(counts=mat))
#' se$stuff <- LETTERS[1:10]
#' se$blah <- runif(10)
#' reducedDims(se) <- list(
#'     PCA=matrix(rnorm(ncol(se)*10), ncol=10),
#'     TSNE=matrix(rnorm(ncol(se)*2), ncol=2)
#' )
#' altExps(se) <- list(spikes=SummarizedExperiment(list(counts=mat[1:2,])))
#'
#' # Staging it: 
#' tmp <- tempfile()
#' dir.create(tmp)
#' info <- stageObject(se, dir=tmp, "rna-seq") 
#'
#' # Loading it back into memory:
#' loadSingleCellExperiment(info, tmp)
#' 
#' @export
#' @importFrom alabaster.se loadSummarizedExperiment
#' @import SingleCellExperiment alabaster.base 
loadSingleCellExperiment <- function(exp.info, project, ...) {
    se <- loadSummarizedExperiment(exp.info, project, ...)
    se <- as(se, "SingleCellExperiment")

    all.reds <- exp.info$single_cell_experiment$reduced_dimensions
    if (length(all.reds)) {
        red.names <- character(length(all.reds))
        for (i in seq_along(all.reds)) {
            red.info <- all.reds[[i]]
            red.exp.info <- acquireMetadata(project, path=red.info$resource$path)
            all.reds[[i]] <- .loadObject(red.exp.info, project=project)
            red.names[i] <- red.info$name
        }
        names(all.reds) <- red.names
        reducedDims(se) <- all.reds
    }

    all.alts <- exp.info$single_cell_experiment$alternative_experiments
    if (length(all.alts)) {
        alt.names <- character(length(all.alts))
        for (i in seq_along(all.alts)) {
            alt.info <- all.alts[[i]]
            alt.exp.info <- acquireMetadata(project, path=alt.info$resource$path)
            all.alts[[i]] <- .loadObject(alt.exp.info, project=project)
            alt.names[i] <- alt.info$name
        }
        names(all.alts) <- alt.names
        altExps(se) <- all.alts
    }

    main.nm <- exp.info$single_cell_experiment$main_experiment_name
    if (!is.null(main.nm)) {
        mainExpName(se) <- main.nm
    }

    se
}

